SELECT * FROM PLAYER_REGISTRATION;
DROP TABLE PLAYER_REGISTRATION;
ALTER TABLE PLAYER_REGISTRATION DROP COLUMN ID 
ALTER TABLE PLAYER_REGISTRATION ADD ID INT IDENTITY(1,1)
CREATE TABLE PLAYER_REGISTRATION
(
ID INT IDENTITY(1,1),
NAME VARCHAR(50),
DEPARTMENT_NAME VARCHAR(50),
CATEGORY VARCHAR(50),
PROPOSAL_PRICE INT,
EMAIL VARCHAR(50),
PASSWORD VARCHAR(50),
IMAGE image,
TOTAL_RUN  INT,
TOTAL_MATCH INT,
TOTAL_WICKET INT,
AVG_RUN INT

);

INSERT INTO PLAYER_REGISTRATION VALUES('SADDAM','CSE','BATSMAN',200000,'saddam@gmail.com','ffghgh','ghdgvhg',78,67,87,65);

DROP TABLE SELECTOR_REGISTRATION;
CREATE TABLE SELECTOR_REGISTRATION
(
ID INT IDENTITY(1,1),
NAME VARCHAR(50),
TEAM_NAME VARCHAR(50),
EMAIL VARCHAR(50),
PASSWORD VARCHAR(50),
IMAGE image

);

DROP TABLE COACH_REGISTRATION

CREATE TABLE COACH_REGISTRATION
(
ID INT IDENTITY(1,1),
NAME VARCHAR(50),
TEAM_NAME VARCHAR(50),
EMAIL VARCHAR(50),
PASSWORD VARCHAR(50),
IMAGE image

);


DROP TABLE BIDDING_TABLE
CREATE TABLE BIDDING_TABLE
(
ID INT IDENTITY(1,1),
TEAM_NAME VARCHAR(250),
PRICE INT,
PLAYER_ID INT,
CATEGORY VARCHAR(50),
);

DROP TABLE TMP_BIDDING_TABLE
CREATE TABLE TMP_BIDDING_TABLE
(
ID INT IDENTITY(1,1),
TEAM_NAME VARCHAR(250),
PRICE INT,
PLAYER_ID INT,
CATEGORY VARCHAR(50),
);

SELECT * FROM BIDDING_TABLE;

select MAX (PRICE)
from TMP_BIDDING_TABLE;

SELECT  P.ID,P.NAME,P.EMAIL,P.CATEGORY,P.DEPARTMENT_NAME,B.TEAM_NAME,B.PRICE
   FROM PLAYER_REGISTRATION P
   RIGHT JOIN BIDDING_TABLE B
   ON P.ID != B.PLAYER_ID;

   SELECT  P.ID,P.NAME,P.EMAIL,P.CATEGORY,P.DEPARTMENT_NAME,B.TEAM_NAME,B.PRICE
   FROM PLAYER_REGISTRATION P
   RIGHT JOIN BIDDING_TABLE B
   ON P.ID != B.PLAYER_ID;

    CREATE TABLE ADMIN_PANEL
(
ID INT IDENTITY(1,1),
EMAIL VARCHAR(250),
PASSWORD varchar(250) 

);
SELECT * FROM  ADMIN_PANEL
INSERT INTO  ADMIN_PANEL VALUES('admin@gmail.com','admin'); 